<a href="https://colab.research.google.com/github/srinivasrom/MyStore/blob/master/EDA_Assg_NYC_Taxi_Starter_Srinivas_Rompala.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **New York City Yellow Taxi Data**

## Objective
In this case study you will be learning exploratory data analysis (EDA) with the help of a dataset on yellow taxi rides in New York City. This will enable you to understand why EDA is an important step in the process of data science and machine learning.

## **Problem Statement**
As an analyst at an upcoming taxi operation in NYC, you are tasked to use the 2023 taxi trip data to uncover insights that could help optimise taxi operations. The goal is to analyse patterns in the data that can inform strategic decisions to improve service efficiency, maximise revenue, and enhance passenger experience.

## Tasks
You need to perform the following steps for successfully completing this assignment:
1. Data Loading
2. Data Cleaning
3. Exploratory Analysis: Bivariate and Multivariate
4. Creating Visualisations to Support the Analysis
5. Deriving Insights and Stating Conclusions

---

**NOTE:** The marks given along with headings and sub-headings are cumulative marks for those particular headings/sub-headings.<br>

The actual marks for each task are specified within the tasks themselves.

For example, marks given with heading *2* or sub-heading *2.1* are the cumulative marks, for your reference only. <br>

The marks you will receive for completing tasks are given with the tasks.

Suppose the marks for two tasks are: 3 marks for 2.1.1 and 2 marks for 3.2.2, or
* 2.1.1 [3 marks]
* 3.2.2 [2 marks]

then, you will earn 3 marks for completing task 2.1.1 and 2 marks for completing task 3.2.2.

---

## Data Understanding
The yellow taxi trip records include fields capturing pick-up and drop-off dates/times, pick-up and drop-off locations, trip distances, itemized fares, rate types, payment types, and driver-reported passenger counts.

The data is stored in Parquet format (*.parquet*). The dataset is from 2009 to 2024. However, for this assignment, we will only be using the data from 2023.

The data for each month is present in a different parquet file. You will get twelve files for each of the months in 2023.

The data was collected and provided to the NYC Taxi and Limousine Commission (TLC) by technology providers like vendors and taxi hailing apps. <br>

You can find the link to the TLC trip records page here: https://www.nyc.gov/site/tlc/about/tlc-trip-record-data.page

###  Data Description
You can find the data description here: [Data Dictionary](https://www.nyc.gov/assets/tlc/downloads/pdf/data_dictionary_trip_records_yellow.pdf)

**Trip Records**



|Field Name       |description |
|:----------------|:-----------|
| VendorID | A code indicating the TPEP provider that provided the record. <br> 1= Creative Mobile Technologies, LLC; <br> 2= VeriFone Inc. |
| tpep_pickup_datetime | The date and time when the meter was engaged.  |
| tpep_dropoff_datetime | The date and time when the meter was disengaged.   |
| Passenger_count | The number of passengers in the vehicle. <br> This is a driver-entered value. |
| Trip_distance | The elapsed trip distance in miles reported by the taximeter. |
| PULocationID | TLC Taxi Zone in which the taximeter was engaged |
| DOLocationID | TLC Taxi Zone in which the taximeter was disengaged |
|RateCodeID |The final rate code in effect at the end of the trip.<br> 1 = Standard rate <br> 2 = JFK <br> 3 = Newark <br>4 = Nassau or Westchester <br>5 = Negotiated fare <br>6 = Group ride |
|Store_and_fwd_flag |This flag indicates whether the trip record was held in vehicle memory before sending to the vendor, aka “store and forward,” because the vehicle did not have a connection to the server.  <br>Y= store and forward trip <br>N= not a store and forward trip |
|Payment_type| A numeric code signifying how the passenger paid for the trip. <br> 1 = Credit card <br>2 = Cash <br>3 = No charge <br>4 = Dispute <br>5 = Unknown <br>6 = Voided trip |
|Fare_amount| The time-and-distance fare calculated by the meter. <br>Extra Miscellaneous extras and surcharges.  Currently, this only includes the 0.50 and 1 USD rush hour and overnight charges. |
|MTA_tax |0.50 USD MTA tax that is automatically triggered based on the metered rate in use. |
|Improvement_surcharge | 0.30 USD improvement surcharge assessed trips at the flag drop. The improvement surcharge began being levied in 2015. |
|Tip_amount |Tip amount – This field is automatically populated for credit card tips. Cash tips are not included. |
| Tolls_amount | Total amount of all tolls paid in trip.  |
| total_amount | The total amount charged to passengers. Does not include cash tips. |
|Congestion_Surcharge |Total amount collected in trip for NYS congestion surcharge. |
| Airport_fee | 1.25 USD for pick up only at LaGuardia and John F. Kennedy Airports|

Although the amounts of extra charges and taxes applied are specified in the data dictionary, you will see that some cases have different values of these charges in the actual data.

**Taxi Zones**

Each of the trip records contains a field corresponding to the location of the pickup or drop-off of the trip, populated by numbers ranging from 1-263.

These numbers correspond to taxi zones, which may be downloaded as a table or map/shapefile and matched to the trip records using a join.

This is covered in more detail in later sections.

---

## **1** Data Preparation

<font color = red>[5 marks]</font> <br>

### Import Libraries

In [1]:
import warnings
!pip install numpy==1.26.4
import numpy as np
!pip install pandas==2.2.3
import pandas as pd
!pip install matplotlib==3.10.0
import matplotlib as plt
!pip install seaborn==0.13.2
import seaborn as sns

Requirement already satisfied: numpy==1.26.4 in /usr/local/lib/python3.12/dist-packages (1.26.4)
Requirement already satisfied: pandas==2.2.3 in /usr/local/lib/python3.12/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas==2.2.3) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas==2.2.3) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas==2.2.3) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas==2.2.3) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas==2.2.3) (1.17.0)
Requirement already satisfied: matplotlib==3.10.0 in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib==3.10.0) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib==3.10.0) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib==3.10.0) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib==3.10.0) (1.5.0)
Requirement already satisfied: numpy>=1.23 in /usr/local/lib/python3.12/dist-packages (from matplotlib==3.10.0) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib==3.10.0) (26.3)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib==3.10.0) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib==3.10.0) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib==3.10.0) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib==3.10.0) (1.17.0)
Requirement already satisfied: seaborn==0.13.2 in /usr/local/lib/python3.12/dist-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /usr/local/lib/python3.12/dist-packages (from seaborn==0.13.2) (1.26.4)
Requirement already satisfied: pandas>=1.2 in /usr/local/lib/python3.12/dist-packages (from seaborn==0.13.2) (2.2.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /usr/local/lib/python3.12/dist-packages (from seaborn==0.13.2) (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn==0.13.2) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn==0.13.2) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn==0.13.2) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn==0.13.2) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn==0.13.2) (26.3)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn==0.13.2) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn==0.13.2) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn==0.13.2) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2->seaborn==0.13.2) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2->seaborn==0.13.2) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn==0.13.2) (1.17.0)

In [2]:
# Import the libraries you will be using for analysis

In [7]:
#Recommended versions
#numpy version: 1.26.4
# pandas version: 2.2.3
# matplotlib version: 3.10.0
# seaborn version: 0.13.2

# Check versions
print("numpy version:", np.__version__)
print("pandas version:", pd.__version__)
print("matplotlib version:", plt.__version__)
print("seaborn version:", sns.__version__)

numpy version: 1.26.4
pandas version: 2.2.3
matplotlib version: 3.10.0
seaborn version: 0.13.2

### **1.1** Load the dataset
<font color = red>[5 marks]</font> <br>

You will see twelve files, one for each month.

To read parquet files with Pandas, you have to follow a similar syntax as that for CSV files.

`df = pd.read_parquet('file.parquet')`

In [17]:
# Try loading one file
df = pd.read_parquet('yellow_tripdata_2023-12.parquet')
df.info()
df.count()
df.shape[0] #no of rows
df.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3376567 entries, 0 to 3376566
Data columns (total 19 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int32
 1   tpep_pickup_datetime   datetime64[us]
 2   tpep_dropoff_datetime  datetime64[us]
 3   passenger_count        float64
 4   trip_distance          float64
 5   RatecodeID             float64
 6   store_and_fwd_flag     object
 7   PULocationID           int32
 8   DOLocationID           int32
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64
 18  Airport_fee            float64
dtypes: datetime64[us](2), float64(12), int32(3), int64(1), object(1)
memory usage: 450.8+ MB

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee
0,1,2023-12-01 00:06:06,2023-12-01 00:15:47,0.0,1.10,1.0,N,230,48,1,10.0,3.5,0.5,1.50,0.0,1.0,16.50,2.5,0.0
1,1,2023-12-01 00:22:26,2023-12-01 00:28:53,0.0,1.50,1.0,N,142,238,1,9.3,3.5,0.5,2.85,0.0,1.0,17.15,2.5,0.0
2,1,2023-12-01 00:59:44,2023-12-01 01:13:22,2.0,2.20,1.0,N,114,186,1,13.5,3.5,0.5,3.00,0.0,1.0,21.50,2.5,0.0
3,2,2023-12-01 00:22:17,2023-12-01 00:30:59,1.0,0.66,1.0,N,79,79,2,7.2,1.0,0.5,0.00,0.0,1.0,12.20,2.5,0.0
4,2,2023-12-01 00:18:16,2023-12-01 00:25:32,2.0,2.20,1.0,N,229,263,1,11.4,1.0,0.5,2.00,0.0,1.0,18.40,2.5,0.0
5,1,2023-12-01 00:13:17,2023-12-01 00:23:53,0.0,5.70,1.0,N,88,141,1,23.3,3.5,0.5,0.00,0.0,1.0,28.30,2.5,0.0
6,2,2023-12-01 00:17:09,2023-12-01 00:33:31,1.0,5.33,1.0,N,45,162,1,24.7,1.0,0.5,3.00,0.0,1.0,32.70,2.5,0.0
7,2,2023-12-01 00:40:49,2023-12-01 00:44:10,1.0,0.76,1.0,N,170,107,1,5.8,1.0,0.5,1.00,0.0,1.0,11.80,2.5,0.0
8,2,2023-12-01 00:19:04,2023-12-01 00:34:36,1.0,3.33,1.0,N,186,209,1,17.7,1.0,0.5,3.40,0.0,1.0,26.10,2.5,0.0
9,1,2023-12-01 00:08:39,2023-12-01 00:16:18,1.0,2.10,1.0,N,163,262,1,12.1,3.5,0.5,3.42,0.0,1.0,20.52,2.5,0.0

How many rows are there? Do you think handling such a large number of rows is computationally feasible when we have to combine the data for all twelve months into one?

To handle this, we need to sample a fraction of data from each of the files. How to go about that? Think of a way to select only some portion of the data from each month's file that accurately represents the trends.

#### Sampling the Data
> One way is to take a small percentage of entries for pickup in every hour of a date. So, for all the days in a month, we can iterate through the hours and select 5% values randomly from those. Use `tpep_pickup_datetime` for this. Separate date and hour from the datetime values and then for each date, select some fraction of trips for each of the 24 hours.

To sample data, you can use the `sample()` method. Follow this syntax:

```Python
# sampled_data is an empty DF to keep appending sampled data of each hour
# hour_data is the DF of entries for an hour 'X' on a date 'Y'

sample = hour_data.sample(frac = 0.05, random_state = 42)
# sample 0.05 of the hour_data
# random_state is just a seed for sampling, you can define it yourself

sampled_data = pd.concat([sampled_data, sample]) # adding data for this hour to the DF
```

This *sampled_data* will contain 5% values selected at random from each hour.

Note that the code given above is only the part that will be used for sampling and not the complete code required for sampling and combining the data files.

Keep in mind that you sample by date AND hour, not just hour. (Why?)

In [20]:
# sampled_data is an empty DF to keep appending sampled data of each hour
sampled_data = pd.DataFrame()
# hour_data is the DF of entries for an hour 'X' on a date 'Y'
hour_data = df[df['tpep_pickup_datetime'].dt.hour == 12]

sample = hour_data.sample(frac = 0.05, random_state = 42)
# sample 0.05 of the hour_data
# random_state is just a seed for sampling, you can define it yourself

sampled_data = pd.concat([sampled_data, sample]) # adding data for this hour to the DF
sampled_data.head()# printing first 5 default rows to check the data is correct or not

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee
3205274,1,2023-12-03 12:57:18,2023-12-03 13:18:41,NaN,0.00,NaN,None,236,230,0,18.0,0.0,0.5,3.30,0.0,1.0,27.30,NaN,NaN
2044236,2,2023-12-18 12:51:07,2023-12-18 13:03:48,1.0,1.54,1.0,N,141,236,1,12.1,0.0,0.5,3.22,0.0,1.0,19.32,2.5,0.0
162792,2,2023-12-02 12:34:55,2023-12-02 12:46:52,1.0,1.80,1.0,N,144,107,1,12.8,0.0,0.5,3.36,0.0,1.0,20.16,2.5,0.0
1316791,1,2023-12-12 12:53:16,2023-12-12 13:06:27,1.0,1.50,1.0,N,100,264,1,13.5,2.5,0.5,3.50,0.0,1.0,21.00,2.5,0.0
2046285,2,2023-12-18 12:14:09,2023-12-18 12:22:41,1.0,0.93,1.0,N,230,161,2,9.3,0.0,0.5,0.00,0.0,1.0,13.30,2.5,0.0

---

**1.1.1** <font color = red>[5 marks]</font> <br>
Figure out how to sample and combine the files.

**Note:** It is not mandatory to use the method specified above. While sampling, you only need to make sure that your sampled data represents the overall data of all the months accurately.

In [9]:
# Sample the data

# It is recommmended to not load all the files at once to avoid memory overload

In [24]:
from google.colab import drive
drive.mount('/content/drive/MyDrive/dataset/')
df = pd.read_parquet(
    '/content/drive/MyDrive/dataset/yellow_tripdata_2023-12.parquet'
)

MessageError: Error: credential propagation was unsuccessful

In [38]:
import os
import pandas as pd

# Change to the directory containing the parquet files
os.chdir('/content')

# Create a list of all the twelve files to read
file_list = os.listdir()

# Initialise an empty dataframe to store the combined sampled data
df = pd.DataFrame()

# Iterate through the list of files and sample one by one:
for file_name in file_list:
    # Only process parquet files that are for yellow taxi data
    if not file_name.endswith('.parquet') or not file_name.startswith('yellow_tripdata_2023-'):
        continue

    try:
        # Construct the full file path
        file_path = os.path.join(os.getcwd(), file_name)

        # Reading the current month's file
        current_month_df = pd.read_parquet(file_path)

        # Ensure 'tpep_pickup_datetime' is in datetime format for operations
        current_month_df['tpep_pickup_datetime'] = pd.to_datetime(current_month_df['tpep_pickup_datetime'])

        # Initialise an empty DataFrame to store sampled data for the current month
        sampled_month_data = pd.DataFrame()

        # Get unique dates in the current month's data
        unique_dates = current_month_df['tpep_pickup_datetime'].dt.date.unique()

        # Loop through each unique date
        for date in unique_dates:
            daily_data = current_month_df[current_month_df['tpep_pickup_datetime'].dt.date == date]
            # Iterate through each hour of the selected date (0 to 23)
            for hour in range(24):
                hour_data = daily_data[daily_data['tpep_pickup_datetime'].dt.hour == hour]

                # Sample 5% of the hourly data randomly
                if not hour_data.empty:
                    sample = hour_data.sample(frac=0.05, random_state=42)
                    # Add data of this hour to the sampled_month_data
                    sampled_month_data = pd.concat([sampled_month_data, sample], ignore_index=True)

        # Concatenate the sampled data of the current month to the main dataframe
        df = pd.concat([df, sampled_month_data], ignore_index=True)

    except Exception as e:
        print(f"Error reading file {file_name}: {e}")

# Display the first few rows of the final combined and sampled dataframe
display(df.head())
print(f"Total sampled rows: {len(df)}")
df.to_parquet('/content/NewDataFrame.parquet')

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,airport_fee
0,2,2023-08-01 00:49:20,2023-08-01 01:32:38,1.0,21.39,2.0,N,132,142,1,70.0,0.0,0.5,11.00,0.00,1.0,86.75,2.5,1.75,NaN
1,2,2023-08-01 00:40:07,2023-08-01 00:51:08,1.0,3.67,1.0,N,137,75,1,16.3,1.0,0.5,4.26,0.00,1.0,25.56,2.5,0.00,NaN
2,1,2023-08-01 00:38:25,2023-08-01 00:51:16,1.0,3.20,1.0,N,100,236,1,16.3,3.5,0.5,5.30,0.00,1.0,26.60,2.5,0.00,NaN
3,2,2023-08-01 00:21:31,2023-08-01 00:52:42,1.0,17.80,2.0,N,132,237,1,70.0,0.0,0.5,16.46,6.55,1.0,98.76,2.5,1.75,NaN
4,2,2023-08-01 00:01:27,2023-08-01 00:21:55,1.0,7.53,1.0,N,236,78,2,32.4,1.0,0.5,0.00,0.00,1.0,37.40,2.5,0.00,NaN

Total sampled rows: 1915511

After combining the data files into one DataFrame, convert the new DataFrame to a CSV or parquet file and store it to use directly.

Ideally, you can try keeping the total entries to around 250,000 to 300,000.

In [36]:
# Store the df in csv/parquet

OSError: Cannot save file into a non-existent directory: 'content'

## **2** Data Cleaning
<font color = red>[30 marks]</font> <br>

Now we can load the new data directly.

In [39]:
# Load the new data file
df1=pd.read_parquet('/content/NewDataFrame.parquet')
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1915511 entries, 0 to 1915510
Data columns (total 20 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int64
 1   tpep_pickup_datetime   datetime64[us]
 2   tpep_dropoff_datetime  datetime64[us]
 3   passenger_count        float64
 4   trip_distance          float64
 5   RatecodeID             float64
 6   store_and_fwd_flag     object
 7   PULocationID           int64
 8   DOLocationID           int64
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64
 18  Airport_fee            float64
 19  airport_fee            float64
dtypes: datetime64[us](2), float64(13), int64(4), object(1)
memory usage: 292.3+ MB

In [40]:
# df.head()
df1.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,airport_fee
0,2,2023-08-01 00:49:20,2023-08-01 01:32:38,1.0,21.39,2.0,N,132,142,1,70.0,0.0,0.5,11.00,0.00,1.0,86.75,2.5,1.75,NaN
1,2,2023-08-01 00:40:07,2023-08-01 00:51:08,1.0,3.67,1.0,N,137,75,1,16.3,1.0,0.5,4.26,0.00,1.0,25.56,2.5,0.00,NaN
2,1,2023-08-01 00:38:25,2023-08-01 00:51:16,1.0,3.20,1.0,N,100,236,1,16.3,3.5,0.5,5.30,0.00,1.0,26.60,2.5,0.00,NaN
3,2,2023-08-01 00:21:31,2023-08-01 00:52:42,1.0,17.80,2.0,N,132,237,1,70.0,0.0,0.5,16.46,6.55,1.0,98.76,2.5,1.75,NaN
4,2,2023-08-01 00:01:27,2023-08-01 00:21:55,1.0,7.53,1.0,N,236,78,2,32.4,1.0,0.5,0.00,0.00,1.0,37.40,2.5,0.00,NaN

In [41]:
# df.info()
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1915511 entries, 0 to 1915510
Data columns (total 20 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int64
 1   tpep_pickup_datetime   datetime64[us]
 2   tpep_dropoff_datetime  datetime64[us]
 3   passenger_count        float64
 4   trip_distance          float64
 5   RatecodeID             float64
 6   store_and_fwd_flag     object
 7   PULocationID           int64
 8   DOLocationID           int64
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64
 18  Airport_fee            float64
 19  airport_fee            float64
dtypes: datetime64[us](2), float64(13), int64(4), object(1)
memory usage: 292.3+ MB

#### **2.1** Fixing Columns
<font color = red>[10 marks]</font> <br>

Fix/drop any columns as you seem necessary in the below sections

In [42]:
#Fix/drop any columns as you seem necessary in the below sections
df1.info()
df1.head()
df1.shape[0]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1915511 entries, 0 to 1915510
Data columns (total 20 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int64
 1   tpep_pickup_datetime   datetime64[us]
 2   tpep_dropoff_datetime  datetime64[us]
 3   passenger_count        float64
 4   trip_distance          float64
 5   RatecodeID             float64
 6   store_and_fwd_flag     object
 7   PULocationID           int64
 8   DOLocationID           int64
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64
 18  Airport_fee            float64
 19  airport_fee            float64
dtypes: datetime64[us](2), float64(13), int64(4), object(1)
memory usage: 292.3+ MB

1915511

**2.1.1** <font color = red>[2 marks]</font> <br>

Fix the index and drop unnecessary columns

In [45]:
# Fix the index and drop any columns that are not needed
df1.reset_index(drop=True, inplace=True)
df1.head()
#drop any columns
df1.drop(columns=['PULocationID'],axis=1, inplace=True)
df1.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,airport_fee
0,2,2023-08-01 00:49:20,2023-08-01 01:32:38,1.0,21.39,2.0,N,142,1,70.0,0.0,0.5,11.00,0.00,1.0,86.75,2.5,1.75,NaN
1,2,2023-08-01 00:40:07,2023-08-01 00:51:08,1.0,3.67,1.0,N,75,1,16.3,1.0,0.5,4.26,0.00,1.0,25.56,2.5,0.00,NaN
2,1,2023-08-01 00:38:25,2023-08-01 00:51:16,1.0,3.20,1.0,N,236,1,16.3,3.5,0.5,5.30,0.00,1.0,26.60,2.5,0.00,NaN
3,2,2023-08-01 00:21:31,2023-08-01 00:52:42,1.0,17.80,2.0,N,237,1,70.0,0.0,0.5,16.46,6.55,1.0,98.76,2.5,1.75,NaN
4,2,2023-08-01 00:01:27,2023-08-01 00:21:55,1.0,7.53,1.0,N,78,2,32.4,1.0,0.5,0.00,0.00,1.0,37.40,2.5,0.00,NaN

**2.1.2** <font color = red>[3 marks]</font> <br>
There are two airport fee columns. This is possibly an error in naming columns. Let's see whether these can be combined into a single column.

In [53]:
# Combine the two airport fee columns
df1 = pd.read_parquet('/content/NewDataFrame.parquet')
df1.reset_index(drop=True, inplace=True)
df1['Airport_fee'] = df1['Airport_fee'].combine_first(df1['airport_fee'])
df1.drop(columns=['airport_fee'],axis=1, inplace=True)
df1.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee
0,2,2023-08-01 00:49:20,2023-08-01 01:32:38,1.0,21.39,2.0,N,132,142,1,70.0,0.0,0.5,11.00,0.00,1.0,86.75,2.5,1.75
1,2,2023-08-01 00:40:07,2023-08-01 00:51:08,1.0,3.67,1.0,N,137,75,1,16.3,1.0,0.5,4.26,0.00,1.0,25.56,2.5,0.00
2,1,2023-08-01 00:38:25,2023-08-01 00:51:16,1.0,3.20,1.0,N,100,236,1,16.3,3.5,0.5,5.30,0.00,1.0,26.60,2.5,0.00
3,2,2023-08-01 00:21:31,2023-08-01 00:52:42,1.0,17.80,2.0,N,132,237,1,70.0,0.0,0.5,16.46,6.55,1.0,98.76,2.5,1.75
4,2,2023-08-01 00:01:27,2023-08-01 00:21:55,1.0,7.53,1.0,N,236,78,2,32.4,1.0,0.5,0.00,0.00,1.0,37.40,2.5,0.00

**2.1.3** <font color = red>[5 marks]</font> <br>
Fix columns with negative (monetary) values

In [54]:
# check where values of fare amount are negative
df1.loc[df1['fare_amount'] < 0, 'fare_amount'].value_counts()

fare_amount
-3.00     2348
-70.00    1330
-7.20      750
-6.50      688
-5.80      672
          ...
-35.01       1
-1.58        1
-97.00       1
-1.47        1
-25.46       1
Name: count, Length: 519, dtype: int64

Did you notice something different in the `RatecodeID` column for above records?

In [57]:
# Analyse RatecodeID for the negative fare amounts

negative_fares = df1[df1['fare_amount'] < 0]
negative_fares
negative_fares[['fare_amount', 'RatecodeID']]

         fare_amount  RatecodeID
103            -87.7         1.0
137            -19.1         1.0
204            -61.1         1.0
913            -70.0         2.0
1199           -14.2         1.0
...              ...         ...
1915231        -10.0         1.0
1915340         -5.1         1.0
1915419        -33.1         1.0
1915453        -10.0         5.0
1915454        -26.8         1.0

[19056 rows x 2 columns]

In [58]:
# Find which columns have negative values
negetiv_Counts= df1.select_dtypes(include=['number']).lt(0).sum()
negetiv_Counts

VendorID                     0
passenger_count              0
trip_distance                0
RatecodeID                   0
PULocationID                 0
DOLocationID                 0
payment_type                 0
fare_amount              19056
extra                     9472
mta_tax                  18241
tip_amount                 117
tolls_amount              1203
improvement_surcharge    18829
total_amount             18840
congestion_surcharge     15051
Airport_fee               2436
dtype: int64

In [63]:
# fix these negative values
numeric_cols = df1.select_dtypes(include='number').columns
df1[numeric_cols] = df1[numeric_cols].clip(lower=0)
df1.head()
#negetiv_Counts= df1.select_dtypes(include=['number']).lt(0).sum()
#negetiv_Counts

VendorID                 0
passenger_count          0
trip_distance            0
RatecodeID               0
PULocationID             0
DOLocationID             0
payment_type             0
fare_amount              0
extra                    0
mta_tax                  0
tip_amount               0
tolls_amount             0
improvement_surcharge    0
total_amount             0
congestion_surcharge     0
Airport_fee              0
dtype: int64

### **2.2** Handling Missing Values
<font color = red>[10 marks]</font> <br>

**2.2.1**  <font color = red>[2 marks]</font> <br>
Find the proportion of missing values in each column

In [66]:
# Find the proportion of missing values in each column
missing_values = df1.isnull().sum()
missing_proportion = missing_values / len(df1)
missing_proportion
missing_prop_new = df1.isnull().mean() * 100
missing_prop_new

VendorID                 0.000000
tpep_pickup_datetime     0.000000
tpep_dropoff_datetime    0.000000
passenger_count          3.400659
trip_distance            0.000000
RatecodeID               3.400659
store_and_fwd_flag       3.400659
PULocationID             0.000000
DOLocationID             0.000000
payment_type             0.000000
fare_amount              0.000000
extra                    0.000000
mta_tax                  0.000000
tip_amount               0.000000
tolls_amount             0.000000
improvement_surcharge    0.000000
total_amount             0.000000
congestion_surcharge     3.400659
Airport_fee              3.400659
dtype: float64

**2.2.2**  <font color = red>[3 marks]</font> <br>
Handling missing values in `passenger_count`

In [71]:
# Display the rows with null values
df1=pd.read_parquet('/content/NewDataFrame.parquet')
df1.reset_index(drop=True, inplace=True)
null_rows = df1[df1.isnull().any(axis=1)]

display(null_rows)
# Impute NaN values in 'passenger_count'

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,airport_fee
0,2,2023-08-01 00:49:20,2023-08-01 01:32:38,1.0,21.39,2.0,N,132,142,1,70.0,0.0,0.5,11.00,0.00,1.0,86.75,2.5,1.75,NaN
1,2,2023-08-01 00:40:07,2023-08-01 00:51:08,1.0,3.67,1.0,N,137,75,1,16.3,1.0,0.5,4.26,0.00,1.0,25.56,2.5,0.00,NaN
2,1,2023-08-01 00:38:25,2023-08-01 00:51:16,1.0,3.20,1.0,N,100,236,1,16.3,3.5,0.5,5.30,0.00,1.0,26.60,2.5,0.00,NaN
3,2,2023-08-01 00:21:31,2023-08-01 00:52:42,1.0,17.80,2.0,N,132,237,1,70.0,0.0,0.5,16.46,6.55,1.0,98.76,2.5,1.75,NaN
4,2,2023-08-01 00:01:27,2023-08-01 00:21:55,1.0,7.53,1.0,N,236,78,2,32.4,1.0,0.5,0.00,0.00,1.0,37.40,2.5,0.00,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1915506,2,2023-02-28 23:28:03,2023-03-01 00:00:31,2.0,5.95,1.0,N,113,37,1,33.1,1.0,0.5,7.62,0.00,1.0,45.72,2.5,0.00,NaN
1915507,1,2023-02-28 23:40:08,2023-02-28 23:46:56,1.0,2.10,1.0,N,170,263,1,10.7,3.5,0.5,3.15,0.00,1.0,18.85,2.5,0.00,NaN
1915508,2,2023-02-28 23:08:26,2023-02-28 23:10:31,1.0,0.50,1.0,N,164,234,1,5.1,1.0,0.5,2.02,0.00,1.0,12.12,2.5,0.00,NaN
1915509,2,2023-02-28 23:14:40,2023-02-28 23:31:39,1.0,0.00,1.0,N,162,151,1,14.2,1.0,0.5,2.00,0.00,1.0,21.20,2.5,0.00,NaN
1915510,1,2023-02-28 23:49:14,2023-03-01 00:06:29,1.0,4.20,1.0,N,230,41,1,20.5,3.5,0.5,5.10,0.00,1.0,30.60,2.5,0.00,NaN

Did you find zeroes in passenger_count? Handle these.

**2.2.3**  <font color = red>[2 marks]</font> <br>
Handle missing values in `RatecodeID`

In [76]:
# Fix missing values in 'RatecodeID'
df1=pd.read_parquet('/content/NewDataFrame.parquet')
df1.reset_index(drop=True, inplace=True)
df1['RatecodeID'].fillna(0, inplace=True)
df1.head()

/tmp/ipykernel_2669/1897534628.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1['RatecodeID'].fillna(0, inplace=True)

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,airport_fee
0,2,2023-08-01 00:49:20,2023-08-01 01:32:38,1.0,21.39,2.0,N,132,142,1,70.0,0.0,0.5,11.00,0.00,1.0,86.75,2.5,1.75,NaN
1,2,2023-08-01 00:40:07,2023-08-01 00:51:08,1.0,3.67,1.0,N,137,75,1,16.3,1.0,0.5,4.26,0.00,1.0,25.56,2.5,0.00,NaN
2,1,2023-08-01 00:38:25,2023-08-01 00:51:16,1.0,3.20,1.0,N,100,236,1,16.3,3.5,0.5,5.30,0.00,1.0,26.60,2.5,0.00,NaN
3,2,2023-08-01 00:21:31,2023-08-01 00:52:42,1.0,17.80,2.0,N,132,237,1,70.0,0.0,0.5,16.46,6.55,1.0,98.76,2.5,1.75,NaN
4,2,2023-08-01 00:01:27,2023-08-01 00:21:55,1.0,7.53,1.0,N,236,78,2,32.4,1.0,0.5,0.00,0.00,1.0,37.40,2.5,0.00,NaN

**2.2.4**  <font color = red>[3 marks]</font> <br>
Impute NaN in `congestion_surcharge`

In [ ]:
# handle null values in congestion_surcharge
df1

Are there missing values in other columns? Did you find NaN values in some other set of columns? Handle those missing values below.

In [ ]:
# Handle any remaining missing values

### **2.3** Handling Outliers
<font color = red>[10 marks]</font> <br>

Before we start fixing outliers, let's perform outlier analysis.

In [ ]:
# Describe the data and check if there are any potential outliers present
# Check for potential out of place values in various columns

**2.3.1**  <font color = red>[10 marks]</font> <br>
Based on the above analysis, it seems that some of the outliers are present due to errors in registering the trips. Fix the outliers.

Some points you can look for:
- Entries where `trip_distance` is nearly 0 and `fare_amount` is more than 300
- Entries where `trip_distance` and `fare_amount` are 0 but the pickup and dropoff zones are different (both distance and fare should not be zero for different zones)
- Entries where `trip_distance` is more than 250  miles.
- Entries where `payment_type` is 0 (there is no payment_type 0 defined in the data dictionary)

These are just some suggestions. You can handle outliers in any way you wish, using the insights from above outlier analysis.

How will you fix each of these values? Which ones will you drop and which ones will you replace?

First, let us remove 7+ passenger counts as there are very less instances.

In [ ]:
# remove passenger_count > 6

In [ ]:
# Continue with outlier handling

In [ ]:
# Do any columns need standardising?

## **3** Exploratory Data Analysis
<font color = red>[90 marks]</font> <br>

In [ ]:
df.columns.tolist()

#### **3.1** General EDA: Finding Patterns and Trends
<font color = red>[40 marks]</font> <br>

**3.1.1** <font color = red>[3 marks]</font> <br>
Categorise the varaibles into Numerical or Categorical.
* `VendorID`:
* `tpep_pickup_datetime`:
* `tpep_dropoff_datetime`:
* `passenger_count`:
* `trip_distance`:
* `RatecodeID`:
* `PULocationID`:
* `DOLocationID`:
* `payment_type`:
* `pickup_hour`:
* `trip_duration`:


The following monetary parameters belong in the same category, is it categorical or numerical?


* `fare_amount`
* `extra`
* `mta_tax`
* `tip_amount`
* `tolls_amount`
* `improvement_surcharge`
* `total_amount`
* `congestion_surcharge`
* `airport_fee`

##### Temporal Analysis

**3.1.2** <font color = red>[5 marks]</font> <br>
Analyse the distribution of taxi pickups by hours, days of the week, and months.

In [ ]:
# Find and show the hourly trends in taxi pickups

In [ ]:
# Find and show the daily trends in taxi pickups (days of the week)

In [ ]:
# Show the monthly trends in pickups

##### Financial Analysis

Take a look at the financial parameters like `fare_amount`, `tip_amount`, `total_amount`, and also `trip_distance`. Do these contain zero/negative values?

In [ ]:
# Analyse the above parameters

Do you think it is beneficial to create a copy DataFrame leaving out the zero values from these?

**3.1.3** <font color = red>[2 marks]</font> <br>
Filter out the zero values from the above columns.

**Note:** The distance might be 0 in cases where pickup and drop is in the same zone. Do you think it is suitable to drop such cases of zero distance?

In [ ]:
# Create a df with non zero entries for the selected parameters.

**3.1.4** <font color = red>[3 marks]</font> <br>
Analyse the monthly revenue (`total_amount`) trend

In [ ]:
# Group data by month and analyse monthly revenue

**3.1.5** <font color = red>[3 marks]</font> <br>
Show the proportion of each quarter of the year in the revenue

In [ ]:
# Calculate proportion of each quarter

**3.1.6** <font color = red>[3 marks]</font> <br>
Visualise the relationship between `trip_distance` and `fare_amount`. Also find the correlation value for these two.

**Hint:** You can leave out the trips with trip_distance = 0

In [ ]:
# Show how trip fare is affected by distance

**3.1.7** <font color = red>[5 marks]</font> <br>
Find and visualise the correlation between:
1. `fare_amount` and trip duration (pickup time to dropoff time)
2. `fare_amount` and `passenger_count`
3. `tip_amount` and `trip_distance`

In [ ]:
# Show relationship between fare and trip duration

In [ ]:
# Show relationship between fare and number of passengers

In [ ]:
# Show relationship between tip and trip distance

**3.1.8** <font color = red>[3 marks]</font> <br>
Analyse the distribution of different payment types (`payment_type`)

In [ ]:
# Analyse the distribution of different payment types (payment_type).

- 1= Credit card
- 2= Cash
- 3= No charge
- 4= Dispute

##### Geographical Analysis

For this, you have to use the *taxi_zones.shp* file from the *taxi_zones* folder.

There would be multiple files inside the folder (such as *.shx, .sbx, .sbn* etc). You do not need to import/read any of the files other than the shapefile, *taxi_zones.shp*.

Do not change any folder structure - all the files need to be present inside the folder for it to work.

The folder structure should look like this:
```
Taxi Zones
|- taxi_zones.shp.xml
|- taxi_zones.prj
|- taxi_zones.sbn
|- taxi_zones.shp
|- taxi_zones.dbf
|- taxi_zones.shx
|- taxi_zones.sbx

 ```

 You only need to read the `taxi_zones.shp` file. The *shp* file will utilise the other files by itself.

We will use the *GeoPandas* library for geopgraphical analysis
```
import geopandas as gpd
```

More about geopandas and shapefiles: [About](https://geopandas.org/en/stable/about.html)


Reading the shapefile is very similar to *Pandas*. Use `gpd.read_file()` function to load the data (*taxi_zones.shp*) as a GeoDataFrame. Documentation: [Reading and Writing Files](https://geopandas.org/en/stable/docs/user_guide/io.html)

In [ ]:
# !pip install geopandas

**3.1.9** <font color = red>[2 marks]</font> <br>
Load the shapefile and display it.

In [ ]:
# import geopandas as gpd


# Read the shapefile using geopandas
zones = # read the .shp file using gpd
zones.head()

Now, if you look at the DataFrame created, you will see columns like: `OBJECTID`,`Shape_Leng`, `Shape_Area`, `zone`, `LocationID`, `borough`, `geometry`.
<br><br>

Now, the `locationID` here is also what we are using to mark pickup and drop zones in the trip records.

The geometric parameters like shape length, shape area and geometry are used to plot the zones on a map.

This can be easily done using the `plot()` method.

In [ ]:
# print(zones.info())
# zones.plot()

Now, you have to merge the trip records and zones data using the location IDs.

**3.1.10** <font color = red>[3 marks]</font> <br>
Merge the zones data into trip data using the `locationID` and `PULocationID` columns.

In [ ]:
# Merge zones and trip records using locationID and PULocationID

**3.1.11** <font color = red>[3 marks]</font> <br>
Group data by location IDs to find the total number of trips per location ID

In [ ]:
# Group data by location and calculate the number of trips

**3.1.12** <font color = red>[2 marks]</font> <br>
Now, use the grouped data to add number of trips to the GeoDataFrame.

We will use this to plot a map of zones showing total trips per zone.

In [ ]:
# Merge trip counts back to the zones GeoDataFrame

The next step is creating a color map (choropleth map) showing zones by the number of trips taken.

Again, you can use the `zones.plot()` method for this. [Plot Method GPD](https://geopandas.org/en/stable/docs/reference/api/geopandas.GeoDataFrame.plot.html#geopandas.GeoDataFrame.plot)

But first, you need to define the figure and axis for the plot.

`fig, ax = plt.subplots(1, 1, figsize = (12, 10))`

This function creates a figure (fig) and a single subplot (ax)

---

After setting up the figure and axis, we can proceed to plot the GeoDataFrame on this axis. This is done in the next step where we use the plot method of the GeoDataFrame.

You can define the following parameters in the `zones.plot()` method:
```
column = '',
ax = ax,
legend = True,
legend_kwds = {'label': "label", 'orientation': "<horizontal/vertical>"}
```

To display the plot, use `plt.show()`.

**3.1.13** <font color = red>[3 marks]</font> <br>
Plot a color-coded map showing zone-wise trips

In [ ]:
# Define figure and axis


# Plot the map and display it

In [ ]:
# can you try displaying the zones DF sorted by the number of trips?

Here we have completed the temporal, financial and geographical analysis on the trip records.

**Compile your findings from general analysis below:**

You can consider the following points:

* Busiest hours, days and months
* Trends in revenue collected
* Trends in quarterly revenue
* How fare depends on trip distance, trip duration and passenger counts
* How tip amount depends on trip distance
* Busiest zones

#### **3.2** Detailed EDA: Insights and Strategies
<font color = red>[50 marks]</font> <br>

Having performed basic analyses for finding trends and patterns, we will now move on to some detailed analysis focussed on operational efficiency, pricing strategies, and customer experience.

##### Operational Efficiency

Analyze variations by time of day and location to identify bottlenecks or inefficiencies in routes

**3.2.1** <font color = red>[3 marks]</font> <br>
Identify slow routes by calculating the average time taken by cabs to get from one zone to another at different hours of the day.

Speed on a route *X* for hour *Y* = (*distance of the route X / average trip duration for hour Y*)

In [ ]:
# Find routes which have the slowest speeds at different times of the day

How does identifying high-traffic, high-demand routes help us?

**3.2.2** <font color = red>[3 marks]</font> <br>
Calculate the number of trips at each hour of the day and visualise them. Find the busiest hour and show the number of trips for that hour.

In [ ]:
# Visualise the number of trips per hour and find the busiest hour

Remember, we took a fraction of trips. To find the actual number, you have to scale the number up by the sampling ratio.

**3.2.3** <font color = red>[2 mark]</font> <br>
Find the actual number of trips in the five busiest hours

In [ ]:
# Scale up the number of trips

# Fill in the value of your sampling fraction and use that to scale up the numbers
sample_fraction =

**3.2.4** <font color = red>[3 marks]</font> <br>
Compare hourly traffic pattern on weekdays. Also compare for weekend.

In [ ]:
# Compare traffic trends for the week days and weekends

What can you infer from the above patterns? How will finding busy and quiet hours for each day help us?

**3.2.5** <font color = red>[3 marks]</font> <br>
Identify top 10 zones with high hourly pickups. Do the same for hourly dropoffs. Show pickup and dropoff trends in these zones.

In [ ]:
# Find top 10 pickup and dropoff zones

**3.2.6** <font color = red>[3 marks]</font> <br>
Find the ratio of pickups and dropoffs in each zone. Display the 10 highest (pickup/drop) and 10 lowest (pickup/drop) ratios.

In [ ]:
# Find the top 10 and bottom 10 pickup/dropoff ratios

**3.2.7** <font color = red>[3 marks]</font> <br>
Identify zones with high pickup and dropoff traffic during night hours (11PM to 5AM)

In [ ]:
# During night hours (11pm to 5am) find the top 10 pickup and dropoff zones
# Note that the top zones should be of night hours and not the overall top zones

Now, let us find the revenue share for the night time hours and the day time hours. After this, we will move to deciding a pricing strategy.

**3.2.8** <font color = red>[2 marks]</font> <br>
Find the revenue share for nighttime and daytime hours.

In [ ]:
# Filter for night hours (11 PM to 5 AM)

##### Pricing Strategy

**3.2.9** <font color = red>[2 marks]</font> <br>
For the different passenger counts, find the average fare per mile per passenger.

For instance, suppose the average fare per mile for trips with 3 passengers is 3 USD/mile, then the fare per mile per passenger will be 1 USD/mile.

In [ ]:
# Analyse the fare per mile per passenger for different passenger counts

**3.2.10** <font color = red>[3 marks]</font> <br>
Find the average fare per mile by hours of the day and by days of the week

In [ ]:
# Compare the average fare per mile for different days and for different times of the day

**3.2.11** <font color = red>[3 marks]</font> <br>
Analyse the average fare per mile for the different vendors for different hours of the day

In [ ]:
# Compare fare per mile for different vendors

**3.2.12** <font color = red>[5 marks]</font> <br>
Compare the fare rates of the different vendors in a tiered fashion. Analyse the average fare per mile for distances upto 2 miles. Analyse the fare per mile for distances from 2 to 5 miles. And then for distances more than 5 miles.

In [ ]:
# Defining distance tiers

##### Customer Experience and Other Factors

**3.2.13** <font color = red>[5 marks]</font> <br>
Analyse average tip percentages based on trip distances, passenger counts and time of pickup. What factors lead to low tip percentages?

In [ ]:
#  Analyze tip percentages based on distances, passenger counts and pickup times

Additional analysis [optional]: Let's try comparing cases of low tips with cases of high tips to find out if we find a clear aspect that drives up the tipping behaviours

In [ ]:
# Compare trips with tip percentage < 10% to trips with tip percentage > 25%

**3.2.14** <font color = red>[3 marks]</font> <br>
Analyse the variation of passenger count across hours and days of the week.

In [ ]:
# See how passenger count varies across hours and days

**3.2.15** <font color = red>[2 marks]</font> <br>
Analyse the variation of passenger counts across zones

In [ ]:
# How does passenger count vary across zones

In [ ]:
# For a more detailed analysis, we can use the zones_with_trips GeoDataFrame
# Create a new column for the average passenger count in each zone.

Find out how often surcharges/extra charges are applied to understand their prevalance

**3.2.16** <font color = red>[5 marks]</font> <br>
Analyse the pickup/dropoff zones or times when extra charges are applied more frequently

In [ ]:
# How often is each surcharge applied?

## **4** Conclusion
<font color = red>[15 marks]</font> <br>

### **4.1** Final Insights and Recommendations
<font color = red>[15 marks]</font> <br>

Conclude your analyses here. Include all the outcomes you found based on the analysis.

Based on the insights, frame a concluding story explaining suitable parameters such as location, time of the day, day of the week etc. to be kept in mind while devising a strategy to meet customer demand and optimise supply.

**4.1.1** <font color = red>[5 marks]</font> <br>
Recommendations to optimize routing and dispatching based on demand patterns and operational inefficiencies

**4.1.2** <font color = red>[5 marks]</font> <br>

Suggestions on strategically positioning cabs across different zones to make best use of insights uncovered by analysing trip trends across time, days and months.

**4.1.3** <font color = red>[5 marks]</font> <br>
Propose data-driven adjustments to the pricing strategy to maximize revenue while maintaining competitive rates with other vendors.